version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PIPEDRIVE_API_TOKEN: ${PIPEDRIVE_API_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - "mysql"
    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: on-failure
