apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 992382561999.dkr.ecr.eu-central-1.amazonaws.com/pipedrive:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mysql-secret
      imagePullSecrets:
        - name: mysecret

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: app
